=== mquinson/MBI/tools/MUST-v1.6/utility/mpi_specification_tool/api-specification.dtd
<!--
  This file is part of MUST (Marmot Umpire Scalable Tool)

  Copyright (C)
    2010-2016 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2010-2018 Lawrence Livermore National Laboratories, United States of America
    2013-2018 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!--unique-name specifies the name of this API-->
<!ELEMENT api-specification (api-headers, functions)>
<!ATTLIST api-specification
   unique-name CDATA #REQUIRED
>

<!-- List of headers for this API. -->
<!ELEMENT api-headers (header)*>

<!-- A header for this API, must be a portable name, e.g. mpi.h. -->
<!ELEMENT header (#PCDATA)>

<!-- List of functions in this API (and the analyses that may be applied to them). -->
<!ELEMENT functions (function)*>

<!--Function of the API
	"Name": specifies the name of the function.
	"return-type": the datatype returned by the function (use "void" for no type).
	"wrapp-everywhere": set this attribute to "yes" (without quotes) if this
	                    API should be wrapped on the application as well on
	                    ALL(!) tool places (Be careful not to wrapp APIs 
	                    used by the tool places to implement their own 
	                    functionality). [optional]
    "is-finalizer": set this attribute to "yes" if this call should cause a shutdown
                    of the tool once called on all application processes. [optional] 

    Rational: there is no such thing as a "is-init" option the first intercepted event
              will initialize the tool. If some communication mechanism is not yet
              available at this time a lazy initialization mechanism allows the 
              execusion to continue and events to be forwarded at a later point in time.
-->
<!ELEMENT function (function-arguments, analyses, operations)>
<!ATTLIST function
   name CDATA #REQUIRED
   return-type CDATA #REQUIRED
   wrapp-everywhere CDATA #IMPLIED
   is-finalizer CDATA #IMPLIED
>

<!--Arguments of a function.-->
<!ELEMENT function-arguments (function-argument | function-array-argument)*>

<!--Argument of a function:
	"name": Attribute name (from default header)
	"type": Type of attribute
	"intent": Optional: "in"/"out"/"inout" - helps for generation of superset wrappers and records, default is "inout"
	"order": index (starting with 0 of the argument in the call) e.g., 0 for first arg, 1 for second, ...
	"typeAfterArg": extra typestring to append after the argument name in declarations, e.g. for "int array[3]" to define the "[3]", optional, default is ""	.
	                        IMPORTANT: arguments with this extension must not be transfered, so eigther process them locally or convert them in an operation.
-->
<!ELEMENT function-argument EMPTY>
<!ATTLIST function-argument
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	intent CDATA #REQUIRED
	order CDATA #REQUIRED
	typeAfterArg CDATA #IMPLIED
>
			
<!--An array argument to a function.
	"name": Attribute name (from default header)
	"type": Type of attribute
	"intent": Optional: "in"/"out"/"inout" - helps for generation of superset wrappers and records, default is "inout"
	"order": index (starting with 0 of the argument in the call) e.g., 0 for first arg, 1 for second, ...
-->
<!ELEMENT function-array-argument (length-argument)>
<!ATTLIST function-array-argument
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	intent CDATA #REQUIRED
	order CDATA #REQUIRED			   
>
				
<!-- The length argument for an array argument.
	"type": either "argument" or "operation"
		- for argument specify the name of the argument that specifies the array length
		 for operation specify the name of the operation (see operations) that specifies the array length
-->
<!ELEMENT length-argument (call-arg-name | op-name)>
<!ATTLIST length-argument
	type CDATA #REQUIRED
>
				
<!-- 
   An argument name from this call
   For analysis/operation inputs you may specify:
   - "USE_CALLNAME" (without quotes) here to refer 
      to the name of the API call instead of to one of 
      its arguments.
   - "USE_CALLID" (without quotes) here to refer to 
      a unique integer (type is int (C)) that identifies
      this call, the id is built by the weaver and no 
      assumptions about its value should be made 
      except that it will b unique for all API calls. 
-->
<!ELEMENT call-arg-name (#PCDATA)>

<!--a name of a operation that can be applied to this call (see operations)
	"group": analysis group of the operation
	"id": if of the operation which is specified in the operation node for this operation
	      (used to distinguish multiple mappings of one operation to one function) 
-->
<!ELEMENT op-name (#PCDATA)>
<!ATTLIST op-name
	group CDATA #REQUIRED
	id CDATA #REQUIRED
>
				
<!--
	List of all the analyses.
	
	The analyses are executed (if multiple of them are present)
	in the specified order. Only exception is when a reduction
	is present in the list of analyses. The reduction will be executed
	first, all remaining analyses will be executed in their specified order
	afterwards.
		
-->
<!ELEMENT analyses (analysis)*>
		
<!--A single analysis:
	"group": Name of the analysis group this analysis comes from
	"name": name of this analysis (must be in the named group)
	             Syntax is: [MODULE_NAME]:[ANALYSIS_NAME]
	             (MODULE_NAME is the name of the analysis module and ANALYSIS_NAME
	              is the name of the analysis function to use)
	"order": "pre"/"post" (pre=before calling actual call, post=after calling actual call)
-->
<!ELEMENT analysis (analysis-arguments)>
<!ATTLIST analysis
	group CDATA #REQUIRED
	name CDATA #REQUIRED
	order CDATA #REQUIRED
>
			
<!-- argument list of this analysis -->
<!ELEMENT analysis-arguments (analysis-argument)*>
					
<!-- An  argument of an analysis.
	"type": "mapped"/"operation"/"operation-len" 
	    - "mapped" is an argument of the call mapped to an argument of the analysis function, 
	    - "operation" uses a process local operation to calculate some information from the inputs of the call and use it as input for the analysis
	    - "operation-len" uses an operation as for the operation type, however receives the array length return of the operation instead of the actual return value of the operation; only valid for operations that return an array
	"analysis-arg-order": Specifies which(0-N) argument of the analysis will get the value of the specified argument/operation-value
-->
<!ELEMENT analysis-argument ((call-arg-name|op-name))>
<!ATTLIST analysis-argument
	type CDATA #REQUIRED
	analysis-arg-order CDATA #REQUIRED
>
						
<!-- 
	List of all operations that can be applied to this call. 

    The operations are executed (if multiple of them are used)
	in the specified order.	
-->
<!ELEMENT operations (operation)*>
				
<!-- A single operation.
	"group": Name of the analysis group this analysis comes from
	"name": name of this analysis (must be in the named group)
	"order": "pre"/"post" (pre=before calling actual call, post=after calling actual call)
	"id": id of this mapping of the operation to the call, used to refer to a particular mapping when reading an array argument which uses an operation for its length argument 
-->
<!ELEMENT operation (operation-arguments)>
<!ATTLIST operation
	group CDATA #REQUIRED
	name CDATA #REQUIRED
	order CDATA #REQUIRED
	id CDATA #REQUIRED
>
			
<!--List of arguments needed for the operation.-->
<!ELEMENT operation-arguments (operation-argument)*>
				
<!--A single argument to an operation.
	"op-arg-order": Specifies which(0-N) argument of the operation will get the value of the specified call argument.
-->
<!ELEMENT operation-argument (call-arg-name)>
<!ATTLIST operation-argument
	op-arg-order CDATA #REQUIRED
>

=== mquinson/MBI/Must/MUST-v1.6/externals/GTI/system-builder/specifications/gti-implicit-api-spec.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE api-specification SYSTEM "/Users/hilbrich/workspace/gti/system-builder/dtd/api-specification.dtd">
<api-specification unique-name="GTI_IMPLICIT_API">
    <api-headers>
        <header>@CMAKE_INSTALL_PREFIX@/src/GtiApi.h</header>
    </api-headers>
    <functions>
        <function return-type="int" name="gtiShutdownNotify"
        	wrapp-down="yes" notify-finalize="yes">
        	<function-arguments></function-arguments>
        	<analyses>
        		<analysis order="pre" name="ShutdownReceiver:receive"
        			group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        	</analyses>
        	<operations></operations>
        </function>
        <function return-type="int" name="gtiRaisePanic"
        	wrapp-everywhere="yes" out-of-order="yes">
        	<function-arguments></function-arguments>
        	<analyses>
        		<analysis order="pre" name="PanicHandler:raisePanic"
        			group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        		<analysis order="pre" name="PanicFilter:propagate"
        			group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        		<analysis order="pre"
        			name="PanicReceiver:notifyRaisePanic" group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        	</analyses>
        	<operations></operations>
        </function>
        <function return-type="int" name="gtiNotifyPanic"
        	wrapp-down="yes">
        	<function-arguments></function-arguments>
        	<analyses>
        		<analysis order="pre" name="PanicReceiver:notifyPanic"
        			group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        		<analysis order="pre" name="FinishNotify:finish" group="MUST_Base">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        	</analyses>
        	<operations></operations>
        </function><function return-type="int" name="gtiNotifyFlush" wrapp-down="yes">
        	<function-arguments></function-arguments>
        	<analyses>
        		<analysis order="pre" name="PanicReceiver:notifyFlush" group="GTI_IMPLICIT">
        			<analysis-arguments></analysis-arguments>
        		</analysis>
        	</analyses>
        	<operations></operations>
        </function>
    	<function return-type="int" name="gtiBreakRequest"
    		wrapp-everywhere="yes" out-of-order="yes">
    		<!--This is indeed a wrapp everywhere to which an aggregation applies and out-of-order; This works since the aggregation that applies here is just a filter indeed--><function-arguments></function-arguments>
    		<analyses>
    			<analysis order="pre"
    				name="BreakReduction:addBreakRequest" group="GTI_IMPLICIT">
    				<analysis-arguments></analysis-arguments>
    			</analysis>
    			<analysis order="pre" name="BreakManager:requestBreak"
    				group="GTI_IMPLICIT">
    				<analysis-arguments></analysis-arguments>
    			</analysis>
    		</analyses>
    		<operations></operations>
    		<created-by>
    			<by name="BreakReduction" group="GTI_IMPLICIT" /></created-by>
    	</function>
    	<function return-type="int" name="gtiBreakConsume"
    		wrapp-everywhere="yes" out-of-order="yes">
    		<function-arguments></function-arguments>
    		<!--This is indeed a wrapp everywhere to which an aggregation applies and out-of-order; This works since the aggregation that applies here is just a filter indeed--><analyses>
    			<analysis order="pre"
    				name="BreakReduction:removeBreakRequest" group="GTI_IMPLICIT">
    				<analysis-arguments></analysis-arguments>
    			</analysis>
    			<analysis order="pre" name="BreakManager:removeBreak"
    				group="GTI_IMPLICIT">
    				<analysis-arguments></analysis-arguments>
    			</analysis>
    		</analyses>
    		<operations></operations>
    	<created-by>
    			<by name="BreakReduction" group="GTI_IMPLICIT" /></created-by></function>
    	<function return-type="int" name="gtiBroadcastBreak"
    		wrapp-down="yes">
    		<function-arguments>
    			<function-argument order="0" name="code" type="int" intent="in"></function-argument>
    		</function-arguments>
    		<analyses>
    			<!--TODO: This is currently a virtual mapping, the enforcer runs on the application; No way to deliver this there (A "test" mechanism will pull this instead)--><analysis order="pre"
    				name="BreakEnforcer:handleBroadcastBreak" group="GTI_IMPLICIT">
    				<analysis-arguments>
    					<analysis-argument type="mapped"
    						analysis-arg-order="0">
    						<call-arg-name>code</call-arg-name>
    					</analysis-argument></analysis-arguments>
    			</analysis>
    		</analyses>
    		<operations></operations>
    		<created-by>
    			<by name="GTI_IMPLICIT" group="BreakManager" /></created-by>
    	</function></functions>
</api-specification>

=== mquinson/MBI/Must/MUST-v1.6/externals/GTI/tests/HelloWeaver/api-spec.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE api-specification SYSTEM "/Users/hilbrich/workspace/must/system-builder/dtd/api-specification.dtd">

<api-specification unique-name="HelloWeaverApi">
    <api-headers></api-headers>
    <functions>
    <function return-type="int" name="MPI_Send" wrapp-everywhere="no">
    		<function-arguments>
    			<function-argument order="0" name="buf" type="void*" intent="in" /><function-argument
    				order="1" name="count" type="int" intent="in" /><function-argument
    				order="2" name="type" type="MPI_Datatype" intent="in" /><function-argument
    				order="3" name="dest" type="int" intent="in" /><function-argument
    				order="4" name="tag" type="int" intent="in" /><function-argument
    				order="5" name="comm" type="MPI_Comm" intent="in" />
    		</function-arguments>
    		<analyses>
    			<analysis order="pre" name="PrintSendRecv:print" group="HelloWeaver">
    				<analysis-arguments>
    					<analysis-argument type="mapped"
    						analysis-arg-order="0">
    						<call-arg-name>count</call-arg-name>
    					</analysis-argument>
    					<analysis-argument type="operation"
    						analysis-arg-order="1">
    						<op-name group="HelloWeaver" id="1">getRank</op-name>
    						
    					</analysis-argument>
    					<analysis-argument type="mapped"
    						analysis-arg-order="2">
    						<call-arg-name>dest</call-arg-name>
    					</analysis-argument>
    					<analysis-argument type="operation"
    						analysis-arg-order="3">
    						<op-name group="HelloWeaver" id="1">return1</op-name>
    						
    					</analysis-argument></analysis-arguments>
    			</analysis>
    		</analyses>
    		<operations>
    			<operation order="pre" name="return1" group="HelloWeaver" id="1">
    				<operation-arguments></operation-arguments>
    			</operation>
    			<operation order="pre" name="getRank" group="HelloWeaver" id="1">
    				<operation-arguments>
    					<operation-argument op-arg-order="0">
    						<call-arg-name>comm</call-arg-name>
    					</operation-argument></operation-arguments>
    			</operation>
    		</operations>
    </function><function return-type="int" name="MPI_Recv" wrapp-everywhere="no">
    		<function-arguments>
    			<function-argument order="0" name="buf" type="void*" intent="in" /><function-argument order="1" name="count" type="int" intent="in" /><function-argument order="2" name="type" type="MPI_Datatype" intent="in" /><function-argument order="3" name="source" type="int" intent="in" /><function-argument order="4" name="tag" type="int" intent="in" /><function-argument order="5" name="comm" type="MPI_Comm" intent="in" /><function-argument
    				order="6" name="status" type="MPI_Status*" intent="out" />
    		</function-arguments>
    		<analyses>
    			<analysis order="pre" name="PrintSendRecv:print" group="HelloWeaver">
    				<analysis-arguments>
    					<analysis-argument type="mapped" analysis-arg-order="0">
    						<call-arg-name>count</call-arg-name>
    					</analysis-argument>
    					<analysis-argument type="operation" analysis-arg-order="1">
    						<op-name group="HelloWeaver" id="1">getRank</op-name>
    						
    					</analysis-argument>
    					<analysis-argument type="mapped" analysis-arg-order="2">
    						<call-arg-name>source</call-arg-name>
    					</analysis-argument>
    					<analysis-argument type="operation" analysis-arg-order="3">
    						<op-name group="HelloWeaver" id="1">return0</op-name>
    						
    					</analysis-argument></analysis-arguments>
    			</analysis>
    		</analyses>
    		<operations>
    			<operation order="pre" name="return0" group="HelloWeaver" id="1">
    				<operation-arguments></operation-arguments>
    			</operation>
    			<operation order="pre" name="getRank" group="HelloWeaver" id="1">
    				<operation-arguments>
    					<operation-argument op-arg-order="0">
    						<call-arg-name>comm</call-arg-name>
    					</operation-argument></operation-arguments>
    			</operation>
    		</operations>
    </function>
    <function return-type="int" name="MPI_Finalize"
    		is-finalizer="yes">
    		<function-arguments>
    			
    		</function-arguments>
    		<analyses></analyses>
    		<operations></operations>
    	</function></functions></api-specification>

=== mquinson/MBI/Must/MUST-v1.6/externals/GTI/tests/example-api-specification.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file is part of GTI (Generic Tool Infrastructure)

  Copyright (C)
    2008-2019 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
    2008-2019 Lawrence Livermore National Laboratories, United States of America
    2013-2019 RWTH Aachen University, Federal Republic of Germany

  See the LICENSE file in the package base directory for details
-->

<!DOCTYPE api-specification SYSTEM "../system-builder/dtd/api-specification.dtd">

<api-specification unique-name="MPI">
    <api-headers><header>mpi.h</header></api-headers>
    <functions>
	<function name="MPI_Test_call" return-type="int">


		<function-arguments>
			<function-array-argument name="arg1" type="int*"
				intent='inout' order="0">
				<length-argument type='argument'>
					<call-arg-name>arg2</call-arg-name>
				</length-argument>
			</function-array-argument>
			<function-argument name="arg2" type="int" intent='in'
				order="1"></function-argument>
			<function-array-argument order="2" name="arg3" type="int*"
				intent="in">
				<length-argument type="operation">
					<op-name group="MPI-Check" id="2">
						get_array_length
					</op-name>

				</length-argument>
			</function-array-argument>
			<function-argument order="3" name="arg4" type="int"
				intent="in"></function-argument>
			<function-argument order="4" name="comm" type="MPI_Comm"
				intent="in" />
			<function-array-argument order="5" name="requests"
				type="MPI_Request*" intent="inout">
				<length-argument type="operation">
					<op-name group="MPI-Check" id="1">
						getCommSize
					</op-name>

				</length-argument>
			</function-array-argument>
			<function-array-argument order="6" name="requests2"
				type="MPI_Request*" intent="inout">
				<length-argument type="operation-len">
					<op-name group="MPI-Check" id="1">
						requests2int
					</op-name>

				</length-argument>
			</function-array-argument>
		</function-arguments>
		<analyses>
			<analysis group="MPI-Check" name="check_array_something"
				order='pre'>
				<analysis-arguments>
					<analysis-argument type='mapped'
						analysis-arg-order="1">
						<call-arg-name>arg1</call-arg-name>
					</analysis-argument>
					<analysis-argument type='operation'
						analysis-arg-order="0">
						<op-name group="MPI-Check" id="1">
							get_array_length
						</op-name>
					</analysis-argument>
				</analysis-arguments>
			</analysis>
			<analysis order="pre" name="checkRequests"
				group="MPI-Check">
				<analysis-arguments>
					<analysis-argument type="operation-len"
						analysis-arg-order="0">
						<op-name group="MPI-Check" id="1">
							requests2int
						</op-name>

					</analysis-argument>
					<analysis-argument type="operation"
						analysis-arg-order="1">
						<op-name group="MPI-Check" id="1">
							requests2int
						</op-name>

					</analysis-argument>
				</analysis-arguments>
			</analysis>
			<analysis order="post" name="test" group="MPI-Check">
				<analysis-arguments>
					<analysis-argument type="mapped" analysis-arg-order="0">
						<call-arg-name>arg4</call-arg-name>
					</analysis-argument></analysis-arguments>
			</analysis>
		</analyses>
		<operations>
			<operation group="MPI-Check" name="get_array_length"
				order="pre" id="1">
				<operation-arguments>
					<operation-argument op-arg-order="0">
						<call-arg-name>arg2</call-arg-name>
					</operation-argument>
				</operation-arguments>
			</operation>
			<operation order="pre" name="get_array_length"
				group="MPI-Check" id="2">
				<operation-arguments>
					<operation-argument op-arg-order="0">
						<call-arg-name>arg4</call-arg-name>
					</operation-argument>
				</operation-arguments>
			</operation>
			<operation order="pre" name="getCommSize" group="MPI-Check"
				id="1">
				<operation-arguments>
					<operation-argument op-arg-order="0">
						<call-arg-name>comm</call-arg-name>
					</operation-argument>
				</operation-arguments>
			</operation>
			<operation order="pre" name="requests2int" group="MPI-Check"
				id="1">
				<operation-arguments>
					<operation-argument op-arg-order="0">
						<call-arg-name>comm</call-arg-name>
					</operation-argument>
					<operation-argument op-arg-order="1">
						<call-arg-name>requests</call-arg-name>
					</operation-argument>
				</operation-arguments>
			</operation>
		</operations>
	</function></functions></api-specification>
